name: my workflow
on: [push]

jobs:
  build:
    name: hello github action
    runs-on: ubuntu-latest
    steps:
      - name: checkout sourse code
        uses: actions/checkout@v3

      - name: echo hello
        uses: echo "hello"
